config/routes.rb
Rails.application.routes.draw do
  root 'gists#index'

  resources :gists do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gist
end

app/models/gist.rb
class Gist < ApplicationRecord
  has_many :comments, dependent: :destroy # new
  validates :src, presence: true, length: { minimum: 8, maximum: 1024 }
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.create(comment_params)
    redirect_to gist_path(@gist)
  end

  def destroy
    @gist = Gist.find(params[:gist_id])
    @comment = @gist.comments.find(params[:id])
    @comment.destroy
    redirect_to gist_path(@gist)
  end
  
  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]

  # GET /gists
  # GET /gists.json
  def index
    @gists = Gist.all
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:src, :lang, :desc)
    end
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  before_action :set_remark, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @remarks = Remark.all
    respond_with(@remarks)
  end

  def show
    respond_with(@remark)
  end

  def new
    @remark = Remark.new
    respond_with(@remark)
  end

  def edit
  end

  def create
    @remark = Remark.new(remark_params)
    @remark.save
    respond_with(@remark)
  end

  def update
    @remark.update(remark_params)
    respond_with(@remark)
  end

  def destroy
    @remark.destroy
    respond_with(@remark)
  end

  private
    def set_remark
      @remark = Remark.find(params[:id])
    end

    def remark_params
      params.require(:remark).permit(:note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment',
              [comment.gist, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: 'btn btn-danger' %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@gist, @gist.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/gists/_form.html.erb
<%= form_for @gist, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :src, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :src, rows: 12, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lang, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :lang, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :desc, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :desc, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  gists_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/gists/edit.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/gists/index.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:src) %></th>
      <th><%= model_class.human_attribute_name(:lang) %></th>
      <th><%= model_class.human_attribute_name(:desc) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gists.each do |gist| %>
      <tr>
        <td><%= gist.id %></td>
          <td><%= gist.src %></td>
          <td><%= gist.lang %></td>
          <td><%= gist.desc %></td>
        <td><%=l gist.created_at, format: :long %></td>
        <td>
          <%= link_to gist_path(gist), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_gist_path(gist), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to gist_path(gist), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_gist_path,
            class: 'btn btn-primary' %>

app/views/gists/new.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/gists/show.html.erb
<%- model_class = Gist -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:src) %></dt>
      <dd><pre class="highlight"><%= raw Rouge.highlight @gist.src, @gist.lang, 'html' %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:lang) %></dt>
      <dd><pre class="prettyprint"><%= @gist.lang %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:desc) %></dt>
      <dd><pre class="prettyprint"><%= @gist.desc %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              gists_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_gist_path(@gist), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              gist_path(@gist),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>

<h2>Comments</h2>

<%= render @gist.comments %>

<h2>Add a comment</h2>

<%= render 'comments/form' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
        <li><%= link_to "About", '/about' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGists50</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/remarks/_form.html.erb
<%= form_for(remark) do |f| %>
  <% if remark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remark.errors.count, "error") %> prohibited this remark from being saved:</h2>

      <ul>
      <% remark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/remarks/edit.html.erb
<h1>Editing Remark</h1>

<%= render 'form', remark: @remark %>

<%= link_to 'Show', @remark %> |
<%= link_to 'Back', remarks_path %>

app/views/remarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remarks</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remarks.each do |remark| %>
      <tr>
        <td><%= remark.note %></td>
        <td><%= link_to 'Show', remark %></td>
        <td><%= link_to 'Edit', edit_remark_path(remark) %></td>
        <td><%= link_to 'Destroy', remark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remark', new_remark_path %>

app/views/remarks/new.html.erb
<h1>New Remark</h1>

<%= render 'form', remark: @remark %>

<%= link_to 'Back', remarks_path %>

app/views/remarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @remark.note %>
</p>

<%= link_to 'Edit', edit_remark_path(@remark) %> |
<%= link_to 'Back', remarks_path %>